server:
  port: 9001
spring:
  application:
    name: running-information-analysis-service
  datasource:
    url: jdbc:mysql://localhost:3306/running_information_analysis_service_db
    username: root
    password: 1
  jpa:
    hibernate:
      ddl-auto: update